version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/belle"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/basm"
    schedule:
      interval: "daily"
