[package]
name = "bfmt"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[profile.release]
lto = true
debug = 0
opt-level = 3
codegen-units = 1
strip = true

