[package]
name = "belle"
version = "0.2.0"
edition = "2021"

[lib]
lints = ["panic"]

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
once_cell = "1.20.1"
ctrlc = "3.4.5"
colored = "2.1.0"
