name: Compact Disc

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t belle-image .

    - name: Create output directory
      run: mkdir -p output

    - name: Copy files from Docker container
      run: |
        docker create --name temp-container belle-image
        docker cp temp-container:/app ./output
        docker rm temp-container

    - name: Clone private repo
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git clone https://github.com/bluegummi/belle-demo.git
        cd belle-demo

        cp -r ../output/* ./

        # Commit and push changes
        git config --global user.email "105593618+BlueGummi@users.noreply.github.com"
        git config --global user.name "Blue Gummi"
        git add .
        git commit -m "Update built files"
        git push origin main
