name: Linux build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build BELLE
        run: cd ./belle && cargo build --release

      - name: Run clippy on BELLE
        run: cd ./belle && cargo clippy -- -D warnings || echo "::warning Clippy found warnings, but continuing."
        continue-on-error: true

      - name: Build the BELLE-assembler
        run: cd ./basm && cargo build --release

      - name: Run clippy on basm
        run: cd ./basm && cargo clippy -- -D warnings || echo "::warning Clippy found warnings, but continuing."
        continue-on-error: true

      - name: Build the BELLE-disassembler
        run: cd ./bdump && make

