name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project for Linux
        run: |
          mkdir bin
          cp -r ./examples ./bin
          mkdir windows-bin
          cp -r ./examples ./bin
          mkdir macos-bin
          cp -r ./examples ./bin


          export RUSTFLAGS="-C target-feature=+crt-static"
          rustup target add x86_64-unknown-linux-musl

          cd belle && cargo build --target x86_64-unknown-linux-musl --release
          cp target/x86_64-unknown-linux-musl/release/belle ../bin && cd ..

          cd basm && cargo build --target x86_64-unknown-linux-musl --release
          cp target/x86_64-unknown-linux-musl/release/basm ../bin && cd ..

          cd bdump && make release && cp bdump ../bin && cd ..
          cd btils && gcc -o bfmt bfmt.c -static && cp bfmt ../bin && cd ..

          sudo apt install zip -y
          tar -czvf belle-nightly-linux-x86_64.tar.gz bin
          zip -r belle-nightly-linux-x86_64.zip bin

      - name: Build project for Windows
        run: |
          sudo apt install mingw-w64 -y

          cd bdump && make release CC=x86_64-w64-mingw32-gcc && cp bdump.exe ../windows-bin && cd ..
          cd btils && x86_64-w64-mingw32-gcc -o bfmt.exe bfmt.c -static && cp bfmt.exe ../windows-bin && cd ..

          rustup target add x86_64-pc-windows-gnu

          cd belle && cargo build --target x86_64-pc-windows-gnu --release
          cp target/x86_64-pc-windows-gnu/release/belle.exe ../windows-bin && cd ..

          cd basm && cargo build --target x86_64-pc-windows-gnu --release
          cp target/x86_64-pc-windows-gnu/release/basm.exe ../windows-bin && cd ..

          tar -czvf belle-nightly-windows-x86_64.tar.gz windows-bin
          zip -r belle-nightly-windows-x86_64.zip windows-bin

      - name: Delete release
        run: |
          git config --global url."https://${{ secrets.DELETE_TOKEN }}@github.com".insteadOf "https://github.com"
          git push --delete origin nightly

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          body: Nightly release for BELLE
          prerelease: true
          token: ${{ secrets.RELEASE_TOKEN }}
          name: Nightly release
          files: |
            belle-nightly-linux-x86_64.tar.gz
            belle-nightly-linux-x86_64.zip
            belle-nightly-windows-x86_64.tar.gz
            belle-nightly-windows-x86_64.zip
