name: Windows build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install dependencies gcc on Windows
        run: |
          choco install mingw
          $env:PATH += ";C:\tools\mingw\bin"

      - name: Test build script (Windows)
        run: .\build.ps1 -n

      - name: Test install script (Windows)
        run: .\install.ps1
